### ISSUE TITLE
每次保存都好慢啊

### ISSUE THREAD

**Issue by zhang-ning** [hushicai/fecs.vim#1]
每次保存都好慢啊

**Comment by hushicai** [comment]
调用外部的checker肯定慢。。。你可以改一下检查的时机，比如设置passive mode，手动触发检查。

**Comment by zhang-ning** [comment]
用 jshint 的时候 没这么慢 － －！ 看来是 fecs 比较慢 －－！issue 开到那边去

**Comment by hushicai** [comment]
你可以先用命令行测试一下，看谁更快。

**Comment by zhang-ning** [comment]
刚测了下，一个30行的文件， jshint 是 秒出，fecs 要 967ms
